### ISSUE TITLE
Feature request: time-resolved panels 

### ISSUE THREAD

**Issue by cscheeder** [mRcSchwering/prevailing-winds#11]
To check for trends it would be helpful to have the option to get the data split per year and month with wind roses for each intervall.

**Comment by mRcSchwering** [comment]
Is there a way to display this "windroses-trend" in one plot? I think with multiple plots the sidepanel would become crowded.

I could however just compute windroses for each year. Then you can see the trend by just clicking through the years.

**Comment by cscheeder** [comment]
A stickplot might solve this?

**Comment by mRcSchwering** [comment]
Not gonna do this. I'm not sure how to visualize this. But it would also require much more data points. This is too much at the moment
