### ISSUE TITLE
Gets confused when you click on long ~ 175 ?

### ISSUE THREAD

**Issue by shearichard** [mRcSchwering/prevailing-winds#5]
Very interesting app, thanks for writing it.

I seem to have found, what I suspect, is a minor defect. I found that the app seems to get confused when you do the following.

1. Visit https://www.prevailing-winds.de/ using recent FF or Chrome on Windows
2. Zoom map out and scroll so that New Zealand is centre of the panel
3. Zoom in so that NZ fills most of the visible panel
4. Click on Wellington (which is Longitude East 174)
5. The text showing where you have clicked reads "41° 46' 16'' S - 183° 7' 12'' W" and the message "only longitudes -180 to 180 are covered" appears.
6. Scroll map so that Paris (in France) is visible , click on Paris (Paris is longitude East 2)
7. The text showing where you have clicked reads "48° 24' 0'' N - 358° 3' 59'' W" and the message "only longitudes -180 to 180 are covered" continues to be displayed.
8. Scroll map so that Los Angeles (in USA) is visible, click on LA (LA is longitude West 118)
9. The text showing where you have clicked reads "33° 56' 36'' N - 476° 11' 29'' W"  and the message "only longitudes -180 to 180 are covered" continues to be displayed.

If, after reloading page, instead of visiting Wellington first I go straight to Paris and then LA everything works as you would expect.

BTW I'm learning React at the moment and being able to read your frontend in the context of seeing the app run is very useful so thanks for that as well the entire app.

**Comment by mRcSchwering** [comment]
I couldn't reproduce it but I have a suspicion.

Could it be that when you scrolled out you dragged the globe "1 turn to much".
This leaflet app (which provides the map) increases longitude monotonously.
_E.g._ if you drag the map all the way to the east - to the eastern border of Russia - you are somewhere close to 180°E.
If you then continue to drag the map eastwards to Alaska the leaftlet app considers this to be 200°E.

My guess is that this is the real bug.
I'm thinking of just writing a function that will convert the 200°E to 160°W when making the backend call.

**Comment by mRcSchwering** [comment]
Sorry, you already confirmed it (183°E). Yes I should fix that.

**Comment by mRcSchwering** [comment]
That should have fixed it:  https://github.com/mRcSchwering/prevailing-winds/commit/aa9998f07fe94bcfc3842b20214e3c045b812539
It's already deployed.

**Comment by shearichard** [comment]
Thanks for that.
